-- ============================================================================
-- SCRIPT DE INSERCIÓN DE PROGRAMAS ACADÉMICOS Y PAÍSES
-- Sistema CASILDA - FNSP
-- Generado a partir de EV-I-02-25 D1.xlsm
-- ============================================================================

-- ============================================================================
-- PROGRAMAS ACADÉMICOS
-- ============================================================================
INSERT INTO programa (id, codigo, nombre, descripcion) VALUES
(1, 'ADM-EMP', 'Administración De Empresas', 'Pregrado'),
(2, 'ADM-SAL', 'Administración En Salud', 'Pregrado'),
(3, 'ADM-SAL-GSA', 'Administración En Salud: Énfasis En Gestión Sanitaria y Ambiental', 'Especialización'),
(4, 'ADM-SAL-GSS', 'Administración En Salud: Gestión De Servicios De Salud', 'Especialización'),
(5, 'ANTRO', 'Antropología', 'Pregrado'),
(6, 'ARCHIV', 'Archivística', 'Pregrado'),
(7, 'ARTE-DRAM', 'Arte Dramático', 'Pregrado'),
(8, 'ARTES-PLAS', 'Artes Plásticas', 'Pregrado'),
(9, 'ASTRO', 'Astronomía', 'Pregrado'),
(10, 'BIBLIO', 'Bibliotecología', 'Pregrado'),
(11, 'BIOING', 'Bioingeniería', 'Pregrado'),
(12, 'BIOLOGIA', 'Biología', 'Pregrado'),
(13, 'CIENC-POL', 'Ciencia Política', 'Pregrado'),
(14, 'CIENC-CULIN', 'Ciencias Culinarias', 'Pregrado'),
(15, 'COM-AUD-MULT', 'Comunicación Audiovisual y Multimedial', 'Pregrado'),
(16, 'COM-SOC-PER', 'Comunicación Social Periodismo', 'Pregrado'),
(17, 'COMUNICACIONES', 'Comunicaciones', 'Pregrado'),
(18, 'CONTA-PUB', 'Contaduría Pública', 'Pregrado'),
(19, 'DERECHO', 'Derecho', 'Pregrado'),
(20, 'DES-TERR', 'Desarrollo Territorial', 'Pregrado'),
(21, 'ECO-ZONAS-COST', 'Ecología De Zonas Costeras', 'Pregrado'),
(22, 'ECONOMIA', 'Economía', 'Pregrado'),
(23, 'ENFERMERIA', 'Enfermería', 'Pregrado'),
(24, 'ENTREN-DEP', 'Entrenamiento Deportivo', 'Pregrado'),
(25, 'ESTADISTICA', 'Estadística', 'Pregrado'),
(26, 'FILOL-HISP', 'Filología Hispánica', 'Pregrado'),
(27, 'FILOSOFIA', 'Filosofía', 'Pregrado'),
(28, 'FISICA', 'Física', 'Pregrado'),
(29, 'GER-SIS-INF-SAL', 'Gerencia En Sistemas De Información En Salud', 'Especialización'),
(30, 'GEST-CULT', 'Gestión Cultural', 'Pregrado'),
(31, 'GEST-ECO-TUR', 'Gestión En Ecología y Turismo', 'Pregrado'),
(32, 'HISTORIA', 'Historia', 'Pregrado'),
(33, 'ING-AEROESP', 'Ingeniería Aeroespacial', 'Pregrado'),
(34, 'ING-AGROIND', 'Ingeniería Agroindustrial', 'Pregrado'),
(35, 'ING-AGROPEC', 'Ingeniería Agropecuaria', 'Pregrado'),
(36, 'ING-AMB', 'Ingeniería Ambiental', 'Pregrado'),
(37, 'ING-AMB-VIRT', 'Ingeniería Ambiental Virtual', 'Pregrado'),
(38, 'ING-BIOQ', 'Ingeniería Bioquímica', 'Pregrado'),
(39, 'ING-CIVIL', 'Ingeniería Civil', 'Pregrado'),
(40, 'ING-ALIM', 'Ingeniería De Alimentos', 'Pregrado'),
(41, 'ING-MAT', 'Ingeniería De Materiales', 'Pregrado'),
(42, 'ING-SIST', 'Ingeniería De Sistemas', 'Pregrado'),
(43, 'ING-SIST-VIRT', 'Ingeniería De Sistemas Virtual', 'Pregrado'),
(44, 'ING-TELEC', 'Ingeniería De Telecomunicaciones', 'Pregrado'),
(45, 'ING-TELEC-VIRT', 'Ingeniería De Telecomunicaciones Virtual', 'Pregrado'),
(46, 'ING-ELEC', 'Ingeniería Eléctrica', 'Pregrado'),
(47, 'ING-ELECTRON', 'Ingeniería Electrónica', 'Pregrado'),
(48, 'ING-ENERG', 'Ingeniería Energética', 'Pregrado'),
(49, 'ING-IND', 'Ingeniería Industrial', 'Pregrado'),
(50, 'ING-IND-VIRT', 'Ingeniería Industrial Virtual', 'Pregrado'),
(51, 'ING-MEC', 'Ingeniería Mecánica', 'Pregrado'),
(52, 'ING-OCEAN', 'Ingeniería Oceanográfica', 'Pregrado'),
(53, 'ING-QUIM', 'Ingeniería Química', 'Pregrado'),
(54, 'ING-SANIT', 'Ingeniería Sanitaria', 'Pregrado'),
(55, 'ING-URB', 'Ingeniería Urbana', 'Pregrado'),
(56, 'INSTRUM-QUIR', 'Instrumentación Quirúrgica', 'Pregrado'),
(57, 'LETRAS-FILOL', 'Letras: Filología Hispánica', 'Pregrado'),
(58, 'LIC-EB-ART-MUS', 'Lic En Educac Básica Énfasis Artístico Música', 'Pregrado'),
(59, 'LIC-EB-HUM-LC', 'Lic. En Educ Básica Énfasis En Humanidades Lengua Castellana', 'Pregrado'),
(60, 'LIC-EB-CN-EA', 'Lic. En Educ. Básica Énfasis En Ccias Naturales y Educ Amb.', 'Pregrado'),
(61, 'LIC-EB-CS', 'Licenciatura Educación Básica Énfasis En Ciencias Sociales', 'Pregrado'),
(62, 'LIC-EB-MAT', 'Licenciatura Educación Básica Énfasis Matemáticas', 'Pregrado'),
(63, 'LIC-ARTES-ESC', 'Licenciatura En Artes Escénicas', 'Pregrado'),
(64, 'LIC-ARTES-PLAS', 'Licenciatura En Artes Plásticas', 'Pregrado'),
(65, 'LIC-CN', 'Licenciatura En Ciencias Naturales', 'Pregrado'),
(66, 'LIC-CS', 'Licenciatura En Ciencias Sociales', 'Pregrado'),
(67, 'LIC-DANZA', 'Licenciatura En Danza', 'Pregrado'),
(68, 'LIC-EB-DANZA', 'Licenciatura En Educación Básica En Danza', 'Pregrado'),
(69, 'LIC-EB-PRIM', 'Licenciatura En Educación Básica Primaria', 'Pregrado'),
(70, 'LIC-ESP-LIT', 'Licenciatura En Educación Español y Literatura', 'Pregrado'),
(71, 'LIC-ED-ESP', 'Licenciatura En Educación Especial', 'Pregrado'),
(72, 'LIC-ED-FIS', 'Licenciatura En Educación Física', 'Pregrado'),
(73, 'LIC-ED-INF', 'Licenciatura En Educación Infantil', 'Pregrado'),
(74, 'LIC-ED-PRIM', 'Licenciatura En Educación Primaria', 'Pregrado'),
(75, 'LIC-ED-ART-PLAS', 'Licenciatura En Educación: Artes Plásticas', 'Pregrado'),
(76, 'LIC-FILOS', 'Licenciatura En Filosofía', 'Pregrado'),
(77, 'LIC-FIS', 'Licenciatura En Física', 'Pregrado'),
(78, 'LIC-LENG-EXT', 'Licenciatura En Lenguas Extranjeras', 'Pregrado'),
(79, 'LIC-LIT-LC', 'Licenciatura En Literatura y Lengua Castellana', 'Pregrado'),
(80, 'LIC-MAT', 'Licenciatura En Matemáticas', 'Pregrado'),
(81, 'LIC-MAT-FIS', 'Licenciatura En Matemáticas y Física', 'Pregrado'),
(82, 'LIC-MUS', 'Licenciatura En Música', 'Pregrado'),
(83, 'LIC-PED-MT', 'Licenciatura En Pedagogía De La Madre Tierra', 'Pregrado'),
(84, 'LIC-PED-INF', 'Licenciatura En Pedagogía Infantil', 'Pregrado'),
(85, 'LIC-TEATRO', 'Licenciatura En Teatro', 'Pregrado'),
(86, 'LIC-LE-ING-FRA', 'Licenciatura Lenguas Extranjeras Con Énfasis Inglés y Francés', 'Pregrado'),
(87, 'LIC-MUS-PIANO', 'Licenciatura Música Instrumentos: Piano', 'Pregrado'),
(88, 'MATEMATICAS', 'Matemáticas', 'Pregrado'),
(89, 'MEDICINA', 'Medicina', 'Pregrado'),
(90, 'MED-VET', 'Medicina Veterinaria', 'Pregrado'),
(91, 'MICRO-IND-AMB', 'Microbiología Industrial y Ambiental', 'Pregrado'),
(92, 'MICRO-BIOANA', 'Microbiología y Bioanálisis', 'Pregrado'),
(93, 'MUSICA', 'Música', 'Pregrado'),
(94, 'MUSICA-CANTO', 'Música-Canto', 'Pregrado'),
(95, 'MUSICA-INSTR', 'Música-Instrumento', 'Pregrado'),
(96, 'NUTRI-DIET', 'Nutrición y Dietética', 'Pregrado'),
(97, 'OCEANOGRAFIA', 'Oceanografía', 'Pregrado'),
(98, 'ODONTOLOGIA', 'Odontología', 'Pregrado'),
(99, 'PEDAGOGIA', 'Pedagogía', 'Pregrado'),
(100, 'PERIODISMO', 'Periodismo', 'Pregrado'),
(101, 'PSICOLOGIA', 'Psicología', 'Pregrado'),
(102, 'QUIMICA', 'Química', 'Pregrado'),
(103, 'QUIM-FARM', 'Química Farmacéutica', 'Pregrado'),
(104, 'SOCIOLOGIA', 'Sociología', 'Pregrado'),
(105, 'TEC-PROF-ATENC-PREHOSP', 'Técnica Profesional En Atención Prehospitalaria', 'Técnica Profesional'),
(106, 'TEC-PROF-AGROPEC', 'Técnico Profesional Agropecuario', 'Técnica Profesional'),
(107, 'TEC-AGROIND', 'Tecnología Agroindustrial', 'Tecnológica'),
(108, 'TEC-BIOMED', 'Tecnología Biomédica', 'Tecnológica'),
(109, 'TEC-ALIM', 'Tecnología De Alimentos', 'Tecnológica'),
(110, 'TEC-ADM-SERV-SAL', 'Tecnología En Administración De Servicios De Salud', 'Tecnológica'),
(111, 'TEC-ARCHIV', 'Tecnología En Archivística', 'Tecnológica'),
(112, 'TEC-ATENC-PREHOSP', 'Tecnología En Atención Prehospitalaria', 'Tecnológica'),
(113, 'TEC-ECO-TUR', 'Tecnología En Ecología y Turismo', 'Tecnológica'),
(114, 'TEC-GEST-INS-AGRO', 'Tecnología En Gestión De Insumos Agropecuarios', 'Tecnológica'),
(115, 'TEC-GEST-SERV-SAL', 'Tecnología En Gestión De Servicios De Salud', 'Tecnológica'),
(116, 'TEC-REG-FARM', 'Tecnología En Regencia De Farmacia', 'Tecnológica'),
(117, 'TEC-SAN-AMB', 'Tecnología En Saneamiento Ambiental', 'Tecnológica'),
(118, 'TEC-QUIM', 'Tecnología Química', 'Tecnológica'),
(119, 'TRAB-SOCIAL', 'Trabajo Social', 'Pregrado'),
(120, 'TRAD-ING-FRA-ESP', 'Traducción Inglés Francés Español', 'Pregrado'),
(121, 'ZOOTECNIA', 'Zootecnia', 'Pregrado'),
(122, 'OTRO', 'Otro-a', 'Otro'),
(123, 'DESCONOCIDO', 'Desconocido-a', 'Desconocido'),
(124, 'NA', 'N/A', 'No aplica');

-- ============================================================================
-- PAÍSES (ISO 3166-1 alfa-3)
-- ============================================================================
INSERT INTO pais (id, codigo, nombre) VALUES
(1, 'AND', 'Andorra'),
(2, 'ARE', 'Emiratos Árabes Unidos'),
(3, 'AFG', 'Afganistán'),
(4, 'ATG', 'Antigua y Barbuda'),
(5, 'AIA', 'Anguila'),
(6, 'ALB', 'Albania'),
(7, 'ARM', 'Armenia'),
(8, 'ANT', 'Antillas Neerlandesas'),
(9, 'AGO', 'Angola'),
(10, 'ATA', 'Antártida'),
(11, 'ARG', 'Argentina'),
(12, 'ASM', 'Samoa Americana'),
(13, 'AUT', 'Austria'),
(14, 'AUS', 'Australia'),
(15, 'ABW', 'Aruba'),
(16, 'ALA', 'Islas Åland'),
(17, 'AZE', 'Azerbaiyán'),
(18, 'BIH', 'Bosnia y Herzegovina'),
(19, 'BRB', 'Barbados'),
(20, 'BGD', 'Bangladesh'),
(21, 'BEL', 'Bélgica'),
(22, 'BFA', 'Burkina Faso'),
(23, 'BGR', 'Bulgaria'),
(24, 'BHR', 'Bahréin'),
(25, 'BDI', 'Burundi'),
(26, 'BEN', 'Benin'),
(27, 'BLM', 'San Bartolomé'),
(28, 'BMU', 'Bermudas'),
(29, 'BRN', 'Brunéi'),
(30, 'BOL', 'Bolivia'),
(31, 'BRA', 'Brasil'),
(32, 'BHS', 'Bahamas'),
(33, 'BTN', 'Bhután'),
(34, 'BVT', 'Isla Bouvet'),
(35, 'BWA', 'Botsuana'),
(36, 'BLR', 'Belarús'),
(37, 'BLZ', 'Belice'),
(38, 'CAN', 'Canadá'),
(39, 'CCK', 'Islas Cocos'),
(40, 'CAF', 'República Centro-Africana'),
(41, 'COG', 'Congo'),
(42, 'CHE', 'Suiza'),
(43, 'CIV', 'Costa de Marfil'),
(44, 'COK', 'Islas Cook'),
(45, 'CHL', 'Chile'),
(46, 'CMR', 'Camerún'),
(47, 'CHN', 'China'),
(48, 'COL', 'Colombia'),
(49, 'CRI', 'Costa Rica'),
(50, 'CUB', 'Cuba'),
(51, 'CPV', 'Cabo Verde'),
(52, 'CXR', 'Islas Christmas'),
(53, 'CYP', 'Chipre'),
(54, 'CZE', 'República Checa'),
(55, 'DEU', 'Alemania'),
(56, 'DJI', 'Yibuti'),
(57, 'DNK', 'Dinamarca'),
(58, 'DMA', 'Domínica'),
(59, 'DOM', 'República Dominicana'),
(60, 'DZA', 'Argel'),
(61, 'ECU', 'Ecuador'),
(62, 'EST', 'Estonia'),
(63, 'EGY', 'Egipto'),
(64, 'ESH', 'Sahara Occidental'),
(65, 'ERI', 'Eritrea'),
(66, 'ESP', 'España'),
(67, 'ETH', 'Etiopía'),
(68, 'FIN', 'Finlandia'),
(69, 'FJI', 'Fiji'),
(70, 'KLK', 'Islas Malvinas'),
(71, 'FSM', 'Micronesia'),
(72, 'FRO', 'Islas Faroe'),
(73, 'FRA', 'Francia'),
(74, 'GAB', 'Gabón'),
(75, 'GBR', 'Reino Unido'),
(76, 'GRD', 'Granada'),
(77, 'GEO', 'Georgia'),
(78, 'GUF', 'Guayana Francesa'),
(79, 'GGY', 'Guernsey'),
(80, 'GHA', 'Ghana'),
(81, 'GIB', 'Gibraltar'),
(82, 'GRL', 'Groenlandia'),
(83, 'GMB', 'Gambia'),
(84, 'GIN', 'Guinea'),
(85, 'GLP', 'Guadalupe'),
(86, 'GNQ', 'Guinea Ecuatorial'),
(87, 'GRC', 'Grecia'),
(88, 'SGS', 'Georgia del Sur e Islas Sandwich del Sur'),
(89, 'GTM', 'Guatemala'),
(90, 'GUM', 'Guam'),
(91, 'GNB', 'Guinea-Bissau'),
(92, 'GUY', 'Guayana'),
(93, 'HKG', 'Hong Kong'),
(94, 'HMD', 'Islas Heard y McDonald'),
(95, 'HND', 'Honduras'),
(96, 'HRV', 'Croacia'),
(97, 'HTI', 'Haití'),
(98, 'HUN', 'Hungría'),
(99, 'IDN', 'Indonesia'),
(100, 'IRL', 'Irlanda'),
(101, 'ISR', 'Israel'),
(102, 'IMN', 'Isla de Man'),
(103, 'IND', 'India'),
(104, 'IOT', 'Territorio Británico del Océano Índico'),
(105, 'IRQ', 'Irak'),
(106, 'IRN', 'Irán'),
(107, 'ISL', 'Islandia'),
(108, 'ITA', 'Italia'),
(109, 'JEY', 'Jersey'),
(110, 'JAM', 'Jamaica'),
(111, 'JOR', 'Jordania'),
(112, 'JPN', 'Japón'),
(113, 'KEN', 'Kenia'),
(114, 'KGZ', 'Kirguistán'),
(115, 'KHM', 'Camboya'),
(116, 'KIR', 'Kiribati'),
(117, 'COM', 'Comoros'),
(118, 'KNA', 'San Cristóbal y Nieves'),
(119, 'PRK', 'Corea del Norte'),
(120, 'KOR', 'Corea del Sur'),
(121, 'KWT', 'Kuwait'),
(122, 'CYM', 'Islas Caimán'),
(123, 'KAZ', 'Kazajstán'),
(124, 'LAO', 'Laos'),
(125, 'LBN', 'Líbano'),
(126, 'LCA', 'Santa Lucía'),
(127, 'LIE', 'Liechtenstein'),
(128, 'LKA', 'Sri Lanka'),
(129, 'LBR', 'Liberia'),
(130, 'LSO', 'Lesotho'),
(131, 'LTU', 'Lituania'),
(132, 'LUX', 'Luxemburgo'),
(133, 'LVA', 'Letonia'),
(134, 'LBY', 'Libia'),
(135, 'MAR', 'Marruecos'),
(136, 'MCO', 'Mónaco'),
(137, 'MDA', 'Moldova'),
(138, 'MNE', 'Montenegro'),
(139, 'MDG', 'Madagascar'),
(140, 'MHL', 'Islas Marshall'),
(141, 'MKD', 'Macedonia'),
(142, 'MLI', 'Mali'),
(143, 'MMR', 'Myanmar'),
(144, 'MNG', 'Mongolia'),
(145, 'MAC', 'Macao'),
(146, 'MTQ', 'Martinica'),
(147, 'MRT', 'Mauritania'),
(148, 'MSR', 'Montserrat'),
(149, 'MLT', 'Malta'),
(150, 'MUS', 'Mauricio'),
(151, 'MDV', 'Maldivas'),
(152, 'MWI', 'Malawi'),
(153, 'MEX', 'México'),
(154, 'MYS', 'Malasia'),
(155, 'MOZ', 'Mozambique'),
(156, 'NAM', 'Namibia'),
(157, 'NCL', 'Nueva Caledonia'),
(158, 'NER', 'Níger'),
(159, 'NFK', 'Islas Norkfolk'),
(160, 'NGA', 'Nigeria'),
(161, 'NIC', 'Nicaragua'),
(162, 'NLD', 'Países Bajos'),
(163, 'NOR', 'Noruega'),
(164, 'NPL', 'Nepal'),
(165, 'NRU', 'Nauru'),
(166, 'NIU', 'Niue'),
(167, 'NZL', 'Nueva Zelanda'),
(168, 'OMN', 'Omán'),
(169, 'PAN', 'Panamá'),
(170, 'PER', 'Perú'),
(171, 'PYF', 'Polinesia Francesa'),
(172, 'PNG', 'Papúa Nueva Guinea'),
(173, 'PHL', 'Filipinas'),
(174, 'PAK', 'Pakistán'),
(175, 'POL', 'Polonia'),
(176, 'SPM', 'San Pedro y Miquelón'),
(177, 'PCN', 'Islas Pitcairn'),
(178, 'PRI', 'Puerto Rico'),
(179, 'PSE', 'Palestina'),
(180, 'PRT', 'Portugal'),
(181, 'PLW', 'Islas Palaos'),
(182, 'PRY', 'Paraguay'),
(183, 'QAT', 'Qatar'),
(184, 'REU', 'Reunión'),
(185, 'ROU', 'Rumanía'),
(186, 'SRB', 'Serbia y Montenegro'),
(187, 'RUS', 'Rusia'),
(188, 'RWA', 'Ruanda'),
(189, 'SAU', 'Arabia Saudita'),
(190, 'SLB', 'Islas Salomón'),
(191, 'SYC', 'Seychelles'),
(192, 'SDN', 'Sudán'),
(193, 'SWE', 'Suecia'),
(194, 'SGP', 'Singapur'),
(195, 'SHN', 'Santa Elena'),
(196, 'SVN', 'Eslovenia'),
(197, 'SJM', 'Islas Svalbard y Jan Mayen'),
(198, 'SVK', 'Eslovaquia'),
(199, 'SLE', 'Sierra Leona'),
(200, 'SMR', 'San Marino'),
(201, 'SEN', 'Senegal'),
(202, 'SOM', 'Somalia'),
(203, 'SUR', 'Surinam'),
(204, 'STP', 'Santo Tomé y Príncipe'),
(205, 'SLV', 'El Salvador'),
(206, 'SYR', 'Siria'),
(207, 'SWZ', 'Suazilandia'),
(208, 'TCA', 'Islas Turcas y Caicos'),
(209, 'TCD', 'Chad'),
(210, 'ATF', 'Territorios Australes Franceses'),
(211, 'TGO', 'Togo'),
(212, 'THA', 'Tailandia'),
(213, 'TZA', 'Tanzania'),
(214, 'TJK', 'Tayikistán'),
(215, 'TKL', 'Tokelau'),
(216, 'TLS', 'Timor-Leste'),
(217, 'TKM', 'Turkmenistán'),
(218, 'TUN', 'Túnez'),
(219, 'TON', 'Tonga'),
(220, 'TUR', 'Turquía'),
(221, 'TTO', 'Trinidad y Tobago'),
(222, 'TUV', 'Tuvalu'),
(223, 'TWN', 'Taiwán'),
(224, 'UKR', 'Ucrania'),
(225, 'UGA', 'Uganda'),
(226, 'USA', 'Estados Unidos de América'),
(227, 'URY', 'Uruguay'),
(228, 'UZB', 'Uzbekistán'),
(229, 'VAT', 'Ciudad del Vaticano'),
(230, 'VCT', 'San Vicente y las Granadinas'),
(231, 'VEN', 'Venezuela'),
(232, 'VGB', 'Islas Vírgenes Británicas'),
(233, 'VIR', 'Islas Vírgenes de los Estados Unidos de América'),
(234, 'VNM', 'Vietnam'),
(235, 'VUT', 'Vanuatu'),
(236, 'WLF', 'Wallis y Futuna'),
(237, 'WSM', 'Samoa'),
(238, 'YEM', 'Yemen'),
(239, 'MYT', 'Mayotte'),
(240, 'ZAF', 'Sudáfrica');
